### PR TITLE
Revert "Merge pull request #173 from heroku/http-429-retry-revival"

### PR DESCRIPTION
**Pull request by voidlock**
This reverts commit 65a225931f13231f5cc574ed596a0026bd5aa89c, reversing
changes made to 038955514dd62ea0ebf56e82d7b771435bd50276.

### CODE REVIEW

**Comment by voidlock** [comment]
👍 tested thoroughly in a devcloud

**Comment by voidlock** [comment]
@heroku/cedar this is ready for a review

**Comment by ferd** [comment]
+1. Any reason why hibernation is getting dropped though?

**Comment by voidlock** [comment]
It didn't hibernate there in the first place. IMO the logic seems to be, if the connection isn't idle, and it's not time to close it. Then assume we're still getting some traffic here and don't hibernate.

All these timeouts are generated via `erlang:start_timer` so they can fire at any time.

**Comment by ferd** [comment]
Sounds good then.

**Comment by voidlock** [comment]
there deployment issues were not related to the code changes. closing this out

**Pull request closed without merging**
