### PR TITLE
Nsync control rods

### PR DESCRIPTION
**Pull request by voidlock**
It is now possible to use the redis config master to synchronize API
read_only control rods via nsync. To flag the API into read_only mode
use
```
SETBIT control_rod 0 1
```
to put the API back into normal operation use:
```
SETBIT control_rod 0 0
```

### CODE REVIEW

**Comment by voidlock** [comment]
This will require changes to the schema's before merging

**Comment by voidlock** [comment]
Build is failing because travis still doesn't have 17.5

**Comment by apg** [comment]
:+1:

**Comment by cyx** [comment]
:+1:

**Pull request merged**
