### PR TITLE
OTP-17 Support

### PR DESCRIPTION
**Pull request by voidlock**
This adds support for running under OTP-17. It sets the preferred OTP version to 17.4.1. Most of the changes are simple type changes to support the newer OTP namespaced types. The biggest change however comes from the nsync dependency. It required [some work](https://github.com/jkvor/nsync/commit/89cfad0ae1b38f252ca6371140473b44426d100b) to make the C portion compile under 17.4.1.

### CODE REVIEW

**Comment by voidlock** [comment]
This is ready for a review @freeformz and @apg.

**Comment by freeformz** [comment]
LGTM, but that doesn't mean much wrt erlang. ;-)

**Comment by apg** [comment]
+1

**Comment by voidlock** [comment]
Travis will fail to build until the
[2015-04-09](http://docs.travis-ci.com/user/build-environment-updates/2015-04-09/#Erlang-VM)
platform update is rolled out.
 
They plan on rolling this tomorrow.

**Pull request merged**
