### PR TITLE
Root ca verification

### PR DESCRIPTION
**Pull request by voidlock**
Adds basic support for root ca verification including max depth checks.

This supersedes the older PR #144.

### CODE REVIEW

**Comment by cyx** [comment]
LGTM (with my untrained eyes :)

**Comment by apg** [comment]
:sheep: it.

**Comment by archaelus** [comment]
Seems good, though which Roots are you trusting in this patch?

Presumably at some point we need to use the `/etc/ssl/certs/*` stuff? A later patch I'm guessing

**Comment by voidlock** [comment]
It defaults to the bundle cacerts.pem bundle found in the priv directory. But can be changed by tweaking [logplex application config](https://github.com/heroku/logplex/blob/7f2cf402edc844177d0f2b593b871486e6bc0759/src/logplex.app.src#L83)

The included bundle is one available at http://curl.haxx.se/ca/cacert.pem

**Pull request merged**
