### PR TITLE
Use https instead of plaintext git in rebar.config

### PR DESCRIPTION
**Pull request by cji**
Fix https://github.com/heroku/prodsec/issues/114

### CODE REVIEW

**Comment by cji** [comment]
@danp ah! thanks, didn't realize that, fixed!

**Comment by cji** [comment]
Not sure if this is failing due to Travis environment issue? There's a warning about an upgrade, and it's failing to fetch ubuntu packages.

**Comment by cji** [comment]
🤔 not sure how/why travis dropped out of the checks on this PR, but trying to close out some old PRs I have open. Travis was previously failing and I think it was due to some package versions getting updated during the lock file change. I reverted those hashes so hopefully tests will pass when they come back.

**Comment by cji** [comment]
Looks like this repo needs to be re-activated in Travis before tests will run 

https://travis-ci.org/heroku/logplex

**Comment by ypaq** [comment]
Reactivated it in travis.

**Pull request merged**
