### PR TITLE
Add control rod to deny creation of tail sessions

### PR DESCRIPTION
**Pull request by ypaq**
New environment variable `DENY_TAIL_SESSIONS` allows to block creation
of tail sessions.

### CODE REVIEW

**Comment by danp** [comment]
Will this affect `heroku logs`, or `heroku logs -t`, or both?

**Comment by ypaq** [comment]
It will affect both.

**Comment by cyx** [comment]
@danp yep! same machinery.

**Comment by ypaq** [comment]
https://github.com/heroku/cedar-ops/issues/539

**Pull request merged**
